### ISSUE TITLE
Problem with Tannic acid 

### ISSUE THREAD

**Issue by pingwangzx** [leelasd/ligpargen#17]
Dear Developers,

I have tried to get the OPLS parameters for tannic acid, but it showed unknown errors. A couple of structures optimized with semi-empirical methods were tested. The molecule has zero charge. Could you please help generate oplsaa parameters for the attached structure? I included several files for the same molecule. In addition, is the limit of 200 atoms still in play if I use command-line LigParGen. Thank you very much.

Best,
Xiao

[tannic.zip](https://github.com/leelasd/ligpargen/files/1961432/tannic.zip)

- [ ] I believe this to be a bug with LigParGen 
- [ ] This is a feature request

## Issue Information
Software name & Version :
Method:

## Actual Behavior

<!--- If suggesting a change/improvement, explain the difference from current behavior —>

**Comment by mc-robinson** [comment]
Hi Xiao,

@leelasd is working on diagnosing the problem with the input to LigParGen. But yes, using the command line you should be able to go over 200 atoms. 

Hope to get back to you shortly with more information!

**Comment by mc-robinson** [comment]
No problem. And yes, please contact Prof. Jorgensen for a copy of BOSS.

**Comment by mc-robinson** [comment]
Okay, so we have tried running the molecule locally, and the problem seems to be the calculation of the CM1A charges. Due to the large number of heavy atoms in Tannic Acid, it seems to be overloading the method of CM1A calculations by exceeding the limit for 2 electron integrals.

It should also be mentioned that the semi-empirical CM1A results for such a large molecule would probably not be good.

**Comment by pingwangzx** [comment]
Thank you very much for your help. I will look into other options for this molecule.
